version: "3.7"
services:
  v2fly:
    image: v2fly/v2fly-core
    container_name: ds-v2ray
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - /etc/localtime:/etc/localtime
      - ./v2fly/conf:/etc/v2ray
      - ./v2fly/log:/var/log/v2ray
      # H2时要在v2ray config配置证书
      - ./caddy/data:/data
    expose:
      # 内部容器使用只需暴露端口
      # 不需要映射到宿主机端口
      # websocket 10086 http/2 10000
      - "10086"
      - "10000"
  speedtest:
    image: adolfintel/speedtest
    restart: always
    container_name: ds-speedtest
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - MODE=standalone
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "81:80"
  caddy:
    image: caddy
    restart: always
    container_name: ds-caddy
    working_dir: /var/www/html
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - /etc/localtime:/etc/localtime
      - ./wwwroot:/var/www/html
      - ./caddy/conf/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - "80:80"
      - "443:443"
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --label-enable --schedule "0 0 3 ? * MON"
